- name: Install Nginx
  become: yes
  become_method: sudo
  apt: pkg=nginx state=installed update_cache=true

- name: Install php-fpm
  become: yes
  become_method: sudo
  apt: pkg=php5-fpm state=installed

- name: Disable Default Site
  become: yes
  become_method: sudo
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Create Web Root
  become: yes
  become_method: sudo
  file: dest=/srv/http mode=775 state=directory owner=www-data group=www-data recurse=yes
